nome = str((input("Qual o seu nome completo  ")).strip())
print("Analisando seu nome...  ")   
print("Seu nome em maiuculas e {}  ".format(str(nome.upper())))
print("Seu nome em letras minusculas e {}  ".format(str(nome.lower())))
print("Seu nome tem ao todo {} ".format(len(nome)-nome.count(" ")))
# print("Seu primeiro nome tem {} letras.".format(nome.find(' ')))
separa = nome.split()
print("Seu primeiro nome e {} ele tem {}.".format(separa[0], len(separa[0])))